### ISSUE TITLE
Support for modded tiles & trees

### ISSUE THREAD

**Issue by ThorianDragonTamer** [muppet9010/Factorio-Biter-Reincarnation#1]
I got this error.
![Capture](https://user-images.githubusercontent.com/47370376/54855520-4bc0cd00-4cbc-11e9-8014-05b901b20cb5.PNG)

**Comment by muppet9010** [comment]
I should have specified that the mod only works with Vanilla tiles and trees at present. Added to mod portal readme on current released version.
What modded tiles and trees where you using btw?

**Comment by ThorianDragonTamer** [comment]
Honestly, I'm not sure. I've updated Factorio and my middle since then.
Most likely asphalt roads, alien biomes, Allen biomes HD, and one of the
sailing /tree growing mods.

**Comment by muppet9010** [comment]
closed as presently this isn't going to happen ever due to complexity. Logged as part of my utility library where the environment specific tree selection logic lives these days.

**Comment by ThorianDragonTamer** [comment]
I totally spaced this, so thanks for taking a look at it! :D
